version: '3.8'

services:
  frontend:
    build:
      context: ./jarvis-frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=https://backend:443/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./jarvis-backend
      dockerfile: Dockerfile.prod
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LLAMAINDEX_PATH=path/to/llamaindex
    ports:
      - "443:443"
    volumes:
      - ./certs:/certs
      - ./llamaindex:/app/llamaindex
    command: flask run --cert=/certs/cert.pem --key=/certs/key.pem
    restart: unless-stopped

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
