version: '3.8'

services:
  frontend:
    build:
      context: ./jarvis-frontend
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=https://backend:443/api
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgres://user:password@db:5432/jarvis
      - CACHE_URL=redis://cache:6379/0
    depends_on:
      - db
      - cache
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jarvis
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:6
    volumes:
      - cache-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  db-data:
  cache-data:
