# Stage 1: Build
FROM python:3.9-slim AS builder
WORKDIR /app
RUN pip install --no-cache-dir -r ../requirements.txt
COPY . .

# Stage 2: Run
FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /app /app
CMD ["flask", "run", "--cert=/certs/cert.pem", "--key=/certs/key.pem"]