# Build stage
FROM node:14 AS builder
WORKDIR /app
COPY jarvis-frontend/package.json jarvis-frontend/yarn.lock ./
RUN yarn install --frozen-lockfile
COPY jarvis-frontend .
RUN yarn build

# Production stage
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]